### PR TITLE
Update Scala version to M1

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by sjrd** [comment]
Could a release be published for 2.13.0-M1, please? This is blocking Scala.js from upgrading to (and subsequently publishing for) 2.13.0-M1, and apparently that's the blocking the rest of the eco-system 😆

**Comment by lrytz** [comment]
I'm working on updated travis / release scripts, will have that done later today. Then it will be very simple to release it against M1, and a good test case.

**Comment by lrytz** [comment]
https://github.com/scala/scala-parallel-collections/pull/24 should be ready now

**Comment by SethTisue** [comment]
fyi @milessabin — this is the actual holdup on getting Scala.js published for 2.13.0-M1

**Comment by lrytz** [comment]
@sjrd version 0.1.2 is now on https://oss.sonatype.org/content/repositories/releases/org/scala-lang/modules/scala-parallel-collections_2.13.0-M1, should be on maven central soon.

**Comment by sjrd** [comment]
Thanks!

**Comment by lrytz** [comment]
It's on central now http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13.0-M1/

**Pull request merged**
