### PR TITLE
ISSUE-104: remove unnecessary mapResult

### PR DESCRIPTION
**Pull request by dengziming**
`mapResult` in `ParIterableLike` will add too many tasks which will potentially bring more bugs such as https://github.com/scala/scala-parallel-collections/issues/104
we just remove the unnecessary mapResult and move the code in which outside.

### CODE REVIEW

**Comment by SethTisue** [comment]
not sure who might be qualified and/or interested in reviewing this: @axel22 @szeiger @julienrf ?

**Comment by julienrf** [comment]
I would like to ask @axel22 to review this PR as he is the original author of the lines that have been changed.

**Comment by axel22** [comment]
These changes look correct as far as I can see.

**Comment by axel22** [comment]
LGTM

**Comment by SethTisue** [comment]
thank you @dengziming!

**Pull request merged**
