### PR TITLE
remove deprecated stuff

### LINKED ISSUE #11: fix deprecation warnings
```
[warn] /home/travis/build/scala/scala-parallel-collections/core/src/main/scala/scala/collection/parallel/mutable/ParTrieMap.scala:78: method readRoot in class TrieMap is deprecated (since 2.12.0): this method will be made private
[warn]     val in = ctrie.readRoot()
[warn]                    ^
[warn] /home/travis/build/scala/scala-parallel-collections/core/src/main/scala/scala/collection/parallel/package.scala:84: trait ThrowableOps in package parallel is deprecated (since 2.11.0): this trait will be removed
[warn]     implicit def throwable2ops(self: Throwable) = new ThrowableOps {
[warn]                                                       ^
[warn] /home/travis/build/scala/scala-parallel-collections/core/src/main/scala/scala/collection/parallel/package.scala:86: class CompositeThrowable in package parallel is deprecated (since 2.11.0): this class will be removed.
[warn]         case (self: CompositeThrowable, that: CompositeThrowable) => new CompositeThrowable(self.throwables ++ that.throwables)
[warn]                                                                          ^
[warn] /home/travis/build/scala/scala-parallel-collections/core/src/main/scala/scala/collection/parallel/package.scala:87: class CompositeThrowable in package parallel is deprecated (since 2.11.0): this class will be removed.
[warn]         case (self: CompositeThrowable, _) => new CompositeThrowable(self.throwables + that)
[warn]                                                   ^
[warn] /home/travis/build/scala/scala-parallel-collections/core/src/main/scala/scala/collection/parallel/package.scala:88: class CompositeThrowable in package parallel is deprecated (since 2.11.0): this class will be removed.
[warn]         case (_, that: CompositeThrowable) => new CompositeThrowable(that.throwables + self)
[warn]                                                   ^
[warn] /home/travis/build/scala/scala-parallel-collections/core/src/main/scala/scala/collection/parallel/package.scala:89: class CompositeThrowable in package parallel is deprecated (since 2.11.0): this class will be removed.
[warn]         case _ => new CompositeThrowable(Set(self, that))
[warn]                       ^
[warn] 6 warnings found
```

### PR DESCRIPTION
**Pull request by SethTisue**
~~not ready for merge, because a coordinated change is needed
in scala/scala~~

fixes #11

### CODE REVIEW

**Comment by SethTisue** [comment]
in ParTrieMap.scala here, we call `TrieMap#readRoot`, which is deprecated in scala/scala and slated to be made package-private

so I need to go actually make it package-private there first, and then depend on the resulting Scala version, before we can make the last deprecation warning go away here

**Comment by szeiger** [comment]
The build failed due to non-existing scaladoc variables. Were there any changes in scala/scala that could cause this?

What's the problem with `TrieMap#readRoot`? We can still make it package-private in `scala.collection` even though we don't "own" this package in the OSGi / Java 9 modules sense.

**Comment by SethTisue** [comment]
> The build failed due to non-existing scaladoc variables. Were there any changes in scala/scala that could cause this?

very likely those were warnings before and now they're errors because I enabled `-Xfatal-warnings` but didn't remember to locally test how that would pan out for Scaladoc generation

as for the root cause of the warnings, I imagine it has to do with the repo split? or perhaps they're older than that.... the scala/scala build is a riot of warnings

**Comment by SethTisue** [comment]
> What's the problem with TrieMap#readRoot

It seems to me that it was resolved by scala/scala#5788.

**Comment by szeiger** [comment]
Ah, makes sense. I remember seeing scaladoc warnings before.

**Pull request merged**
