### PR TITLE
Cross build with Scala Native

### LINKED ISSUE #262: Support for Scala Native 0.5.x
In order to proceed towards a stable 0.5.0 version of Scala Native, it would really help to support the RC versions. I have a dependency on this library.

Consensus has been pretty consistent that downstream will only support the new version and not 0.4.0 in addition to the new version. I don't speak directly for the community or for Scala Native in a formal sense but this is my understanding.

According to @WojciechMazur 

> It would be also a good idea to support scala-parallel-collections. These work correctly in Scala 2.12, but were removed to separate project in 2.13

### PR DESCRIPTION
**Pull request by WojciechMazur**
Resolves #262

### CODE REVIEW

**Review by joroKr21 — APPROVED** [review]
Nice 👍

**Comment by SethTisue** [comment]
Zero source code changes. Amazing!

Is there any Native-specific documentation we ought to provide as part of this? (like, I don't know... Is configuring the thread pool any different?)

**Comment by WojciechMazur** [comment]
I believe the configuration should be exactly the same as on the JVM by providing a custom ExecutionContext / ForkJoinPool. The only exception could be system properties-based configs (which are missing in this codebase) - these cannot be preconfigured at startup but need to be set at runtime.

**Comment by SethTisue** [comment]
ticket on rolling a release: https://github.com/scala/scala-parallel-collections/issues/286

**Pull request merged**
