### PR TITLE
keep serialization stability on Scala 2.13.9

### PR DESCRIPTION
**Pull request by SethTisue**
fixes scala/scala-dev#809

tested locally with:

```
set Global / resolvers += "integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
++2.13.9-bin-e623b15
junit/testOnly scala.SerializationStabilityTest
```

### CODE REVIEW

**Comment by SethTisue** [comment]
this was failing on Scala 3.0.2. maybe it will pass on 3.1.3-RC3?

**Comment by SethTisue** [comment]
nope. @lrytz perhaps you'd like to dig into this? else one or both of us can return to it after Dublin

**Comment by lrytz** [comment]
Hmm... Scala 3 generates a slightly different classfile, which means a different generated SVUID if the file was compiled with Scala 2. What I would do is update the scala-3 version of the test (https://github.com/scala/scala-parallel-collections/blob/main/junit/src/test/scala-3/scala/SerializationStabilityTest.scala) so that it passes after this change. The risk that anyone is deserializing across different Scala 3 versions is probably 0.

**Comment by SethTisue** [comment]
okay will do

**Pull request merged**
